language: node_js
node_js:
  - '7.6'
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script: npm run travis-script
after_script:
  - npm report-coverage
before_script:
  - npm install -g gulp-cli
deploy:
  app: test-ci
  provider: heroku
  api_key:
    secure: auBdU0dKRsULQaMsTFnt0Gal/YSJSQFgSz1bONqYkm+TFnSlC2W3w1BNUFAqyrUceWT90aieBRau4G9yFNUE6/MGFaxH7a2B1CYraXE2sHXQQ5+vts2mIyeMNnAWiQTiqpMjBvIVKkfLzgOdYgTgNwIZ4b6bSRqd9upCAZAbhoipFNpChSdPtKS6iAr3V7PXlHl1GOyPqURVmhi5r3snHAWk70tp5RZMEX/jSvXnQDFK+YlNyKS4LwpyS1B9UB1C+wLx5MCuijFi6l02ETD21LN3JQG800MKukG3/6Zhec2JbCzlRMMphHJk0fX2bshIpLAEuZzEd0dvOYVTJ5maMuCUijq07PTTIuTOLKCcoZFuKm+sypF9jv4lEVfQUp+dEchrfQyixJNgbuEP6qbbo00i4xzMxPMrj/l0cPI0LSSgupLS4CrrmwiVvqTx30Cr0MXY+sU2uGMNOABHVce6S7QoNv0jst9RlDd2Ab+Q+akD7/ZABGFpOE8AIADP4y9gZcoj92nn8uOpRnISgYGjdBYM9iqksTxiWqwgGWKKWXhr5Gjvc1Ql6y4LBHvtKNDHliMwGs7N9f5PLpWitY50q7NMzwuMH8mO95+WXQ1MFxFORp04p+rscTx7jr8Q+uF/SWZ20BmmmAYIyqMIvREEHKMK/s5xlT7QvrQV/ZENMKU=
after_success:
  - git config --global user.name "Surabhi Sharma"
  - git config --global user.email surabhisharma.226005@gmail.com
  - if [ "$TRAVIS_BRANCH" == "develop" ] ; then git add dist/ ; git checkout -b release ; git commit -m "Dist" ; git push heroku release:master ; fi
  # - git add dist/
  # - git checkout -b release
  # - git commit -m "Dist"
  # - git push heroku release:master
  # - fi


#- if [ "$TRAVIS_BRANCH" == "master" ] ; then npm run deploy ; else echo "Skipping after_success" ; fi