language: node_js
node_js:
  - '7.6'
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script: npm run travis-script
after_script:
  - npm report-coverage
before_script:
  - npm install -g gulp-cli
deploy:
  app: $APP_NAME
  provider: $PROVIDER
  api_key:
    secure: $TRAVIS_SECURE_API_KEY
after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ] ; then 
    if [ "$TRAVIS_PULL_REQUEST" == "true" ] ; then bash travis.sh ; fi ; fi
